apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   kubernetes.io/change-cause: "Change port to 110"
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sba10/k8s-hands-on:v2
---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090