apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: cont1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
spec:
  containers:
    - name: cont1
      image: nginx:alpine
