apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-test
  labels:
    app: rs-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-labek
  template:
    metadata:
      labels:
        app: pod-labek
    spec:
      containers:
        - name: cont1
          image: python:3.7-alpine
          command: ['sh', '-c', 'echo "cont1" > index.html && python -m http.server 8081']